### ISSUE TITLE
NetworkTraining::compileNetwork doesnt create hidden layers

### ISSUE THREAD

**Issue by feldi** [juergen1976/GeneticNeuralNetworks#1]
Hello,
in `NetworkTraining::compileNetwork` the code for creating the hidden layers is wrong and should look somewhat like the code below, I think.

Greetings,
feldi 

```java
        // Add layers between
        int layer_id = 1;
        if (nb_layers > 1) {
        	for (layer_id = 1; layer_id < nb_layers; layer_id++) {
        		builder.layer(layer_id, new DenseLayer.Builder() // create the hidden layers
        				.nIn(nb_neurons)
        				.nOut(nb_neurons)
        				.activation(activation)
        				.weightInit(WeightInit.XAVIER)
        				.build());
        	}
        }

        // Output Layer
        builder.layer(layer_id, new OutputLayer.Builder(LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD) //create hidden layer
                .nIn(nb_neurons)
                .nOut(outputNum)
                .activation(Activation.SOFTMAX)
                .weightInit(WeightInit.XAVIER)
                .build());

**Comment by juergen1976** [comment]
Thx a lot! Fixed.

**Comment by feldi** [comment]
Hallo!
Der Fix ist leider nicht ganz korrekt aus meinem Beispiel übernommen, der
output layer muss auch eine andere LayerId bekommen.
Viele Grüße aus Hamburg,
Peter Feldtmann


Jürgen Toth <notifications@github.com> schrieb am Sa., 9. März 2019, 11:17:

**Comment by juergen1976** [comment]
Danke. ist gefixt. der output layer muss nb_layers-1 sein. Mindestanzahl von layern ist nun 2.

**Comment by feldi** [comment]
Hallo,
leider noch ein kleiner Fehler:

        // Add layers between input layer and output layer
        if (nb_layers > 2) {
            for (int layer_id = 1; layer_id < nb_layers-1; layer_id++) {
                builder.layer(0, new DenseLayer.Builder() //create the
hidden layers
                .nIn(nb_neurons)
                .nOut(nb_neurons)
                .activation(activation)
                .weightInit(WeightInit.XAVIER)
                .build());
            }
        }

sollte lauten:

        // Add layers between input layer and output layer
        if (nb_layers > 2) {
            for (int layer_id = 1; layer_id < nb_layers-1; layer_id++) {
                 builder.layer(layer_id, new DenseLayer.Builder() //create
the hidden layer <<--- layer_id statt 0 !
                .nIn(nb_neurons)
                .nOut(nb_neurons)
                .activation(activation)
                .weightInit(WeightInit.XAVIER)
                .build());
            }
        }

Danke und Gruß,
Peter Feldtmann

Am Sa., 9. März 2019 um 13:28 Uhr schrieb Jürgen Toth <
notifications@github.com>:

**Comment by juergen1976** [comment]
Thx! fixed.
